name: Deploy to GitHub Pages

on:
  push:
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build pages
        run: |
          pip install -r requirements.txt
          make html
          touch build/html/.nojekyll
      - name: Deploy to GitHub Pages
        uses: ksato-dev/sphinx-test@main
        
        env:
          BUILD_DIR: build/html
          GH_PAT: ${{ secrets.GH_PAT }}
